.\" This is a comment
.\" Contact Owen@thelinuxblog.com
.TH man 1 "7 December 2012" ".1" "Man Page Example"
.SH NAME
happy \- happy eyeballs probing tool
.SH SYNOPSIS
.BR happy " [" \-ms "] [" "\-p port" "] [" "\-q nqueries" "] [" "\-t timeout" "] [" "\-d delay" "] [" "\-f file" "] " target "..."
.SH DESCRIPTION
.I happy
is a simple TCP happy eyeballs probing tool. It uses non-blocking
connect() calls to establish connections concurrently to a number of
possible endpoints. This tool is particularly useful to determine
whether happy eyeball applications will use IPv4 or IPv6 if both are
available.
.PP
A common usage is in combination with watch(1):
.PP
watch -d -- happy -s www.google.com www.bing.com www.yahoo.com
.SH OPTIONS
.TP
.B -m
Produce more compact machine readable output.
.TP
.B -s
Sort the results for all endpoints of a given target. Sorting is based
on the average time it took to establish TCP connections. (Failed attempts
are ignored.)
.TP
.BI \-p " port"
Establish TCP connections to the given
.I port
instead of the default port 80. This option can be used multiple times
to probe multiple port simultaneously.
.TP
.BI \-q " nqueries"
Run
.I nqueries
attempts to establish a TCP connection for each IP address of the
given targets. The default is 3 attempts.
.TP
.BI \-t " timeout"
Set the timeout to
.I timeout
milliseconds. The default is 2000 milliseconds (= 2 seconds).
.TP
.BI \-d " delay"
Set the delay between TCP connection attempts to
.I delay
milliseconds. The default is 25 milliseconds.
.TP
.BI \-f " file"
Read the targets from the 
.I file
or from standard input if the file name is a single dash (`-').
.SH SEE ALSO
watch (1), RFC 6555
.SH LIMITATIONS
The tool does not check whether the endpoints of a given target all
provide the same service. Hence, it is possible to impact the results
by setting up 'fake' servers that do not provide the service tested and
which are designed and deployed with the only purpose to provide fast
connection setup times.
.SH BUGS
Likely, but we will try to fix them if we can reproduce them.
.SH AUTHOR
Juergen Schoenwaelder <j.schoenwaelder@jacobs-university.de>
